-- insert_test_data.sql

INSERT INTO heroes (
    name,
    hit_points,
    date_of_birth,
    race,
    hero_class,
    level,
    alignment,
    strength,
    dexterity,
    constitution,
    intelligence,
    wisdom,
    charisma,
    armor_class,
    speed,
    initiative,
    proficiency_bonus,
    saving_throws,
    skills,
    languages,
    features,
    equipment,
    background,
    attack,
    damage
) VALUES (
             'Anders B',
             80,
             '1977-05-17',
             'Human',
             'Paladin',
             0,
             'Chaotic Good',
             18,
             12,
             16,
             10,
             14,
             16,
             18,
             5,
             2,
             3,
             'Wisdom, Charisma',
             'Athletics, Religion',
             'Common, Templar',
             'Divine Smite, Lay on Hands',
             'Plate armor, Longsword, Shield',
             'Acolyte',
             10,
             '1d8 + 4'
         );