server:
    port: 8080
spring:
  r2dbc:
      username: MP77
      password: IDecreeAndDeclareWarOnShitePerformance
      port: 5434
      database: cars_db
      host: localhost
      url: r2dbc:postgresql://localhost:5434/heroes_db
      pool:
          enabled: true
          initial-size: 5
          max-size: 20